### ISSUE TITLE
Simulation cannot activate controller

### ISSUE THREAD

**Issue by ZhongmouLi** [clearpathrobotics/clearpath_simulator#50]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS 2 Humble
 -  installed:
 - Package version: 0.2.6-1jammy.20240911.170638

 **Expected behaviour**
lunched simulation properly and it able to move with keyboard controller or gazebo control panel

 **Actual behaviour**
[spawner-8] [ERROR] [1728999008.200920895] [a200_0000.spawner_platform_velocity_controller]: Failed to activate controller

![image](https://github.com/user-attachments/assets/0ffe4ae7-19d4-4338-afe9-9eb2bbeaec01)

**To Reproduce**
Provide the steps to reproduce:
1. install simulator following https://docs.clearpathrobotics.com/docs/ros/tutorials/simulator/install
2. ros2 launch clearpath_gz simulation.launch.py

**Other notes**
https://pastebin.com/kX8S79Cw

**Comment by daylanc** [comment]
@ZhongmouLi, were you able to find a solution? I'm running into the same issue. When attempting to move, I see "Failed to activate controller" and "platform_velocity_controller can't accept new commands. subscriber is inactive."

**Comment by KushnirDmytro** [comment]
I've got the same one.
Issue is that simulation has to be running in order to launch controller.

The launch files pipeline is broken and does not allow you to have running sim from the launch file parameters.
You can click the "play" button while simulation is loading, if you have a lucky moment.

Go to pkg `clearpath_gz/launch/gz_sim_launch.gz`

And there when arg `gz_sim = ...` is created adjust to have
```
    # Gazebo Simulator
    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource([gz_sim_launch]),
        launch_arguments=[
            ('gz_args', [LaunchConfiguration('world'),
                         '.sdf',
                         ' -v 4 -r ', # Add the "-r" flag to run simulation from start
                         ' --gui-config ',
                         gui_config])
        ]
    )
```
 The elegant solution would be to fix the parameter passing to via this launcher link, but this should fix the issue
 
 (toggling of simulation pause in `.world` file was not working for me, not sure why)
 
 UPD: Issue Duplication detected [here]( https://github.com/clearpathrobotics/clearpath_simulator/issues/46#issuecomment-2336835500)

**Comment by ZhongmouLi** [comment]
@daylanc The solution is what @KushnirDmytro said.

You have to click "Play" as soon as you can. Then it should work.

**Comment by daylanc** [comment]
Thank you @KushnirDmytro and @ZhongmouLi. Running the sim on start fixed the problem and I was able to move the rover around!

**Comment by hilary-luo** [comment]
Closed as part of https://github.com/clearpathrobotics/clearpath_simulator/pull/52
